### ISSUE TITLE
Wrong indentation for try..except..else / for..else / while..else

### ISSUE THREAD

**Issue by f0k** [kbrose/vsc-python-indent#53]
**Minimal code example:**

What the code looks like before pressing `enter`:

```python
if True:
    try:
        pass
    except:
        pass
    else:|
```

What I want the code to look like after pressing `enter`:

```python
if True:
    try:
        pass
    except:
        pass
    else:
        |
```

What the code actually looks like after pressing `enter`:

```python
if True:
    try:
        pass
    except:
        pass
else:
    |
```

Same problem if instead of `try ... except ... else`, I do `for ... else` or `while ... else`.

Arguably the current behavior may be what many users expect and thus be left as is. For me, personally, an option to disable automatic `else:` dedentation would also work. In any case, this is not crucial at all, I'm fine correcting the automation once in a while. Thanks again for all the key presses saved so far!

**Comment by kbrose** [comment]
Should be updated in 1.8.0

I added `try` (and `for`) as other alternatives for what `else` can match when finding what previous line to dedent to. This should result in your desired behavior above, but also result in the desired behavior for

```python
if True:
    try:
        pass
    except:
        pass
        else:|
```

> For me, personally, an option to disable automatic else: dedentation would also work.

Are you having other troubles with the dedentation (`else`, `elif`, `except`, `finally`)? I tried hard to make sure it would only dedent when it was unambiguously sure that it _should_ dedent (but I missed the case you describe here). E.g. it will not dedent in this case since it is ambiguous:

```python
if True:
    try:
        pass
    except:
        pass
    else:|
```

**Comment by f0k** [comment]
> Should be updated in 1.8.0

Installed, tested, works perfectly!

> Are you having other troubles with the dedentation

No, not at all, thank you! It's just that I don't use it, and I wasn't sure if fixing the behavior I described was an option, given that except..else, for..else and while..else are rarely used.

> I tried hard to make sure it would only dedent when it was unambiguously sure

Seems to be a good principle.

Again, thanks a lot for maintaining this, and for the extremely quick fixes! :1st_place_medal:
