### ISSUE TITLE
Possibility to transfer functionality to other languages?

### ISSUE THREAD

**Issue by MarkDVerhagen** [kbrose/vsc-python-indent#81]
Love this extension so much the only thing going against it is that it makes me want one for R even more!

Was wondering what your views are on extending the current extension to work with other languages or whether such an extension would logically need to be build up from scratch.

Keep up the great work!

**Comment by kbrose** [comment]
Hello Mark,

I think it would make the most sense for someone else to maintain a similar extension for R. I don't use R, and wouldn't want to take on maintenance for something which I myself wouldn't use. The name of this extension is also pretty python-focused, it would be confusing for R users to be told to download the "Python Indent" package.

This code uses the very permissive MIT license, and I'm happy for you or anyone to take part of this code and run with it. In fact, nothing could make me happier -- that's why I open sourced it!

That said, I am happy to answer any questions on how/why I did things, to the best of my abilities. It's been years since I've written some of this code, and my memory might be a little flaky.
