### ISSUE TITLE
Publish to open-vsx.org?

### ISSUE THREAD

**Issue by hl2guide** [kbrose/vsc-python-indent#88]
Please consider publishing this extension to: https://open-vsx.org/

So that users of VSCodium can use it too.

**Comment by kbrose** [comment]
Hello @hl2guide! Can you share more about what open-vsx is? The website wants me to create an account just to read their "free whitepaper".

**Comment by hl2guide** [comment]
Please refer to: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

**Comment by kbrose** [comment]
It seems like it my extension was [scraped by the open-vsx bot](https://open-vsx.org/extension/KevinRose/vsc-python-indent) since this issue was opened, so I'm going to close it. 

But do note: I am not the one publishing that extension, so I cannot verify that it actually matches the extension I publish to the VS Code Marketplace.

If in doubt, you can always download the .vsix files I attach to each tag ([example](https://github.com/kbrose/vsc-python-indent/releases/tag/v1.15.0)) and install the extension from it.
